/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ppp
 */
import java.awt.event.KeyEvent;
import java.net.ConnectException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import java.sql.CallableStatement;

public class searchstud extends javax.swing.JFrame {

    /**
     * Creates new form searchstud
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sql=null;
    String name=null;
    String studid= null;
    String studname=null;
    CallableStatement cStmt=null;
    String semid=null;
    
    public searchstud() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        new globalmethods().filltable(tbl_student,"%%");
    }
    
    public searchstud(String name,String semid) {
        initComponents();
        conn=javaconnect.ConnecrDb();
        this.name=name;
        this.semid=semid;
        new globalmethods().filltable(tbl_student,"%"+name);
        jLabel1.setText(semid);
    }
    
    /*
    public void filltable(){
        
        try {    
            sql="select * from student where lname like '%"+name+"%'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
          
            tbl_student.setModel(DbUtils.resultSetToTableModel(rs));     
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();
        cmd_ok = new javax.swing.JButton();
        cmd_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentMouseClicked(evt);
            }
        });
        tbl_student.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_studentKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_studentKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_student);

        cmd_ok.setText("Ok");
        cmd_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_okActionPerformed(evt);
            }
        });

        cmd_cancel.setText("Cancel");
        cmd_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 452, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(cmd_cancel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cmd_ok, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(cmd_ok)
                        .add(18, 18, 18)
                        .add(cmd_cancel)
                        .add(49, 49, 49)
                        .add(jLabel1))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-575)/2, (screenSize.height-452)/2, 575, 452);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentMouseClicked
        // TODO add your handling code here:
            try {
                int row=tbl_student.getSelectedRow();
                String Table_click= (tbl_student.getModel().getValueAt(row, 0).toString());    
                cStmt=conn.prepareCall("{call proc_studentClick(?)}");
                cStmt.setString(1, Table_click);
                cStmt.execute();
                rs=cStmt.getResultSet(); 
                if(rs.next()){
                    studid=rs.getString("studid");               
                    studname=rs.getString("name");
                }
            //this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //new printing(studid,studname).setVisible(true);
    }//GEN-LAST:event_tbl_studentMouseClicked

    private void tbl_studentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_studentKeyPressed
        // TODO add your handling code here:
        int row=tbl_student.getSelectedRow();
        if(row<0){
            
            JOptionPane.showMessageDialog(null, "Please select a student!");
        }else{
             if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
                new printing(studid,studname,semid).setVisible(true);
                this.dispose();
        }
        }
       
        
    }//GEN-LAST:event_tbl_studentKeyPressed

    private void tbl_studentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_studentKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tbl_studentKeyReleased

    private void cmd_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new printing(studid,studname,semid).setVisible(true);
    }//GEN-LAST:event_cmd_cancelActionPerformed

    private void cmd_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_okActionPerformed
        // TODO add your handling code here:
                int row=tbl_student.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a student!");
        }else{
            new printing(studid,studname,semid).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_cmd_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchstud().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_cancel;
    private javax.swing.JButton cmd_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_student;
    // End of variables declaration//GEN-END:variables
}
